tap 'fforster/gitlab-mcp', 'https://gitlab.com/fforster/homebrew-gitlab-mcp.git'
brew 'gitlab-mcp'

brew 'ca-certificates'
brew 'mas'

cask '1password-cli'
cask 'bartender'
cask 'brave-browser'
cask 'browserino'
cask 'caffeine'
cask 'calibre'
cask 'claude'
cask 'claude-code'
cask 'cloudflare-warp'
cask 'cyberduck'
cask 'drivedx'
cask 'emacs-app'
cask 'firefox'
cask 'font-fira-code'
cask 'fork'
cask 'gcloud-cli'
cask 'ghostty'
cask 'gimp'
cask 'gcloud-cli'
cask 'google-drive'
cask 'iterm2'
cask 'libreoffice'
cask 'lm-studio'
cask 'lulu'
cask 'megasync'
cask 'mullvad-vpn'
cask 'notion'
cask 'obsidian'
cask 'portfolioperformance'
cask 'rar'
cask 'rectangle'
cask 'rio'
cask 'scroll-reverser'
cask 'smlnj'
cask 'spotify'
cask 'tableplus'
cask 'tailscale-app'
cask 'telegram'
cask 'todoist-app'
cask 'utm'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
cask 'zen'

mas 'MEGA VPN', id: 6456784858
